# Generated by Django 3.2 on 2021-10-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contact_us_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_us',
            new_name='Feedback',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='comment',
            new_name='comments',
        ),
    ]
